"use strict";
myAdminApp.factory('DataUsers', function() {
  return {
    get : function() {
      return [
        {
            "id": "53dcd9125cb714cc5d297cd1",
            "index": 0,
            "picture": "http://placehold.it/128x128",
            "age": 28,
            "eyeColor": "green",
            "name": "Rush Harrington",
            "gender": "male",
            "company": "LIQUICOM",
            "email": "rushharrington@liquicom.com",
            "phone": "+1 (965) 581-3336",
            "address": "495 Oak Street, Neibert, South Dakota, 440",
            "about": "Incididunt id occaecat deserunt Lorem occaecat commodo sint. Lorem amet ex esse amet sunt reprehenderit veniam do reprehenderit et mollit. Nisi esse eu ullamco mollit fugiat officia in. Esse Lorem id elit ullamco deserunt anim exercitation est. Mollit eu deserunt occaecat consectetur anim ipsum.\r\n",
            "registered": "2014-07-20T03:40:31 -02:00",
            "role": "user"
        },
        {
            "id": "53dcd9123cfae36130e4c8e3",
            "index": 1,
            "picture": "http://placehold.it/128x128",
            "age": 31,
            "eyeColor": "brown",
            "name": "Lessie Shelton",
            "gender": "female",
            "company": "PYRAMI",
            "email": "lessieshelton@pyrami.com",
            "phone": "+1 (885) 574-3073",
            "address": "468 Cortelyou Road, Glidden, New Hampshire, 4893",
            "about": "Labore minim est minim laborum reprehenderit quis irure aute amet. Veniam exercitation fugiat veniam incididunt. Consequat eiusmod elit elit qui. Minim nostrud est esse nostrud est Lorem. Do excepteur amet minim eu. Incididunt proident labore sint id sunt aliqua amet ad est id laborum minim.\r\n",
            "registered": "2014-04-24T04:32:10 -02:00",
            "role": "user"
        },
        {
            "id": "53dcd912749f84d5ad5c0858",
            "index": 2,
            "picture": "http://placehold.it/128x128",
            "age": 23,
            "eyeColor": "brown",
            "name": "Holmes Whitley",
            "gender": "male",
            "company": "DAIDO",
            "email": "holmeswhitley@daido.com",
            "phone": "+1 (849) 534-2234",
            "address": "893 Varet Street, Imperial, Montana, 712",
            "about": "Sint deserunt adipisicing ea sint in cupidatat aliqua. Veniam et et commodo sint proident qui cillum mollit. Eu aliquip minim veniam et adipisicing occaecat anim cillum veniam mollit ex.\r\n",
            "registered": "2014-03-18T00:15:38 -01:00",
            "role": "admin"
        },
        {
            "id": "53dcd912c3474e24bd3b9b6e",
            "index": 3,
            "picture": "http://placehold.it/128x128",
            "age": 40,
            "eyeColor": "green",
            "name": "Rivera Clayton",
            "gender": "male",
            "company": "NEPTIDE",
            "email": "riveraclayton@neptide.com",
            "phone": "+1 (997) 570-3284",
            "address": "584 Crystal Street, Devon, Illinois, 6272",
            "about": "Consectetur nostrud velit commodo non quis incididunt qui magna tempor cupidatat voluptate. Irure in exercitation deserunt culpa ex esse incididunt sit exercitation. Voluptate eiusmod velit nostrud excepteur incididunt mollit. Ut ex proident id magna cupidatat sint excepteur velit elit sit ipsum sit sint officia.\r\n",
            "registered": "2014-01-29T18:30:42 -01:00",
            "role": "admin"
        },
        {
            "id": "53dcd912fc555bcd07821a8a",
            "index": 4,
            "picture": "http://placehold.it/128x128",
            "age": 21,
            "eyeColor": "blue",
            "name": "Vinson Dunlap",
            "gender": "male",
            "company": "PUSHCART",
            "email": "vinsondunlap@pushcart.com",
            "phone": "+1 (829) 501-2805",
            "address": "371 Portland Avenue, Concho, Louisiana, 4652",
            "about": "Duis in magna aliquip excepteur est ea est non cupidatat proident officia. Quis pariatur do consequat deserunt commodo fugiat laboris. Dolore aliquip laboris nostrud ut fugiat. Veniam et labore reprehenderit sunt commodo irure cupidatat nisi nulla. Irure Lorem adipisicing dolore cillum adipisicing irure anim aliquip. Est laborum elit incididunt Lorem.\r\n",
            "registered": "2014-03-21T22:08:49 -01:00",
            "role": "admin"
        },
        {
            "id": "53dcd9120c1c72cda059b8d9",
            "index": 5,
            "picture": "http://placehold.it/128x128",
            "age": 35,
            "eyeColor": "blue",
            "name": "Carrillo Booker",
            "gender": "male",
            "company": "FANFARE",
            "email": "carrillobooker@fanfare.com",
            "phone": "+1 (906) 503-2908",
            "address": "592 Meeker Avenue, Needmore, District Of Columbia, 2667",
            "about": "Proident officia ipsum aliquip sint dolor. Commodo cillum Lorem aliqua dolore velit irure consequat est incididunt pariatur esse veniam nulla. Eiusmod minim incididunt nisi amet sit amet ullamco occaecat et deserunt culpa fugiat irure aliqua. Ea ullamco est deserunt laborum aliquip sunt cillum et sunt sunt dolor do proident.\r\n",
            "registered": "2014-07-16T20:50:42 -02:00",
            "role": "user"
        },
        {
            "id": "53dcd912f994e809ab975901",
            "index": 6,
            "picture": "http://placehold.it/128x128",
            "age": 28,
            "eyeColor": "green",
            "name": "Silvia Munoz",
            "gender": "female",
            "company": "AUSTECH",
            "email": "silviamunoz@austech.com",
            "phone": "+1 (876) 510-3795",
            "address": "113 Harrison Avenue, Hackneyville, Washington, 1788",
            "about": "Nulla labore sit ea tempor Lorem est nisi. Reprehenderit magna pariatur qui mollit sint nisi. Excepteur est aliqua proident occaecat commodo proident cillum quis id velit ipsum ullamco aliqua. Et ex mollit irure laboris et sint esse dolor. Officia magna ipsum veniam qui exercitation nostrud pariatur reprehenderit magna ea reprehenderit adipisicing in dolor. Lorem aute velit magna reprehenderit voluptate occaecat.\r\n",
            "registered": "2014-04-26T17:01:25 -02:00",
            "role": "user"
        },
        {
            "id": "53dcd912277b4f8d1e361d83",
            "index": 7,
            "picture": "http://placehold.it/128x128",
            "age": 40,
            "eyeColor": "green",
            "name": "May Hayes",
            "gender": "male",
            "company": "FURNIGEER",
            "email": "mayhayes@furnigeer.com",
            "phone": "+1 (968) 418-2948",
            "address": "763 Baycliff Terrace, Warren, Tennessee, 735",
            "about": "Cillum magna do eiusmod nostrud ad voluptate eiusmod esse amet voluptate. Do reprehenderit est commodo pariatur. Culpa dolore aliquip adipisicing ea qui. Incididunt eiusmod Lorem magna Lorem ut officia sit elit in reprehenderit non. Ipsum magna dolor sint id et eiusmod dolor est deserunt duis ea consectetur cupidatat aliquip.\r\n",
            "registered": "2014-01-29T07:50:24 -01:00",
            "role": "admin"
        },
        {
            "id": "53dcd912402c5cd796bc8b00",
            "index": 8,
            "picture": "http://placehold.it/128x128",
            "age": 22,
            "eyeColor": "blue",
            "name": "Vicky Hampton",
            "gender": "female",
            "company": "PHORMULA",
            "email": "vickyhampton@phormula.com",
            "phone": "+1 (910) 471-3741",
            "address": "749 Clinton Avenue, Muse, Alaska, 7290",
            "about": "In ea exercitation nostrud ut ad dolore pariatur est excepteur non tempor mollit consectetur cupidatat. Velit reprehenderit commodo magna magna mollit incididunt veniam excepteur nostrud aute quis nostrud. Nulla est veniam ad laboris elit laboris in commodo ut et laborum dolor. Ex Lorem aliqua consectetur consectetur minim. Irure cupidatat aute ut minim.\r\n",
            "registered": "2014-05-28T11:14:58 -02:00",
            "role": "user"
        },
        {
            "id": "53dcd9120b6b92894290ab1f",
            "index": 9,
            "picture": "http://placehold.it/128x128",
            "age": 27,
            "eyeColor": "blue",
            "name": "Russo Byers",
            "gender": "male",
            "company": "ZENOLUX",
            "email": "russobyers@zenolux.com",
            "phone": "+1 (844) 520-2198",
            "address": "760 Rock Street, Welda, North Dakota, 1843",
            "about": "Dolor sunt ullamco amet amet est id. Officia duis nisi exercitation deserunt et adipisicing do minim exercitation qui nisi et. Veniam ad nostrud anim voluptate anim cillum dolore adipisicing laboris. Aliqua culpa incididunt irure duis consectetur laborum exercitation minim velit. Incididunt sunt ullamco ad in reprehenderit Lorem aliquip magna exercitation culpa irure dolore. Esse laboris non magna labore. Aute officia incididunt nostrud ullamco ea commodo duis do enim amet aliquip aute exercitation amet.\r\n",
            "registered": "2014-02-20T06:49:25 -01:00",
            "role": "user"
        },
        {
            "id": "53dcd912b8fb900ece94913e",
            "index": 10,
            "picture": "http://placehold.it/128x128",
            "age": 28,
            "eyeColor": "blue",
            "name": "Mattie Copeland",
            "gender": "female",
            "company": "MACRONAUT",
            "email": "mattiecopeland@macronaut.com",
            "phone": "+1 (959) 448-2389",
            "address": "977 Boerum Street, Greensburg, Georgia, 2041",
            "about": "Ipsum eu anim amet dolor in minim. Aliqua sit culpa ea cupidatat anim do tempor proident proident eu. Esse minim ullamco anim nostrud. Anim voluptate irure ea consectetur sit aute pariatur ea. Aliqua quis minim irure dolore Lorem magna cupidatat aliqua nulla. Id aute magna ut dolor veniam veniam cupidatat enim consectetur. Esse adipisicing id officia cupidatat consequat ipsum et culpa anim.\r\n",
            "registered": "2014-02-12T17:37:03 -01:00",
            "role": "user"
        },
        {
            "id": "53dcd91277f550fa09b11558",
            "index": 11,
            "picture": "http://placehold.it/128x128",
            "age": 26,
            "eyeColor": "brown",
            "name": "Cassie Mathis",
            "gender": "female",
            "company": "JUNIPOOR",
            "email": "cassiemathis@junipoor.com",
            "phone": "+1 (966) 591-2532",
            "address": "118 Leonard Street, Cataract, Marshall Islands, 6162",
            "about": "Amet nulla est nisi in cillum quis in culpa exercitation proident. Sint proident ullamco ex amet ea laboris fugiat exercitation commodo proident irure. Amet non tempor ea magna dolore fugiat. Nulla anim irure veniam ea reprehenderit. Sint voluptate elit dolor laborum in. Aliqua officia quis commodo ipsum ad. Aute labore ipsum duis commodo cillum.\r\n",
            "registered": "2014-07-17T18:52:33 -02:00",
            "role": "admin"
        }
      ];
    }
  }
})
